# Dependencies
#markdown:         kramdown
#highlighter:      rouge
gems:
    - jekyll-paginate
    - jekyll-gist

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Alex Gude
tagline:          'Scientist'
description:      'Data scientist'
url:              http://alexgude.com
baseurl:          /

author:
name:           'Alexander Gude'
url:             http://alexgude.com

paginate:         5

# Custom vars
version:          2.1.0

github:
repo:           https://github.com/poole/hyde
