# Dependencies
gems:
    - jekyll-paginate
    - jekyll-gist
    - jekyll-sitemap

# Permalinks
permalink:        pretty

# Setup
title:            Alex Gude
tagline:          'Data Scientist'
description:      'The home page and blog of Alexander Gude'
url:              http://alexgude.com
baseurl:          /

author:           'Alexander Gude'

# Blog
paginate:         5
paginate_path:    "/blog/page:num/"

# SASS
sass:
    sass_dir: _sass
    style:    compressed
