# Dependencies
gems:
    - jekyll-paginate
    - jekyll-gist
    - jekyll-sitemap
    - jekyll-seo-tag
    - jekyll-feed
    - jekyll-redirect-from

# Setup
author:
    name: "Alexander Gude"
    first: "Alexander"
    last: "Gude"
    twitter: "alex_gude"
    github: "agude"

title:            "Alex Gude"
tagline:          "Data Scientist"
description:      "The home page and blog of Alexander Gude"
logo:             /files/headshot.jpg

# URL
url:              http://alexgude.com
baseurl:          ""
name:             "AlexGude.com"

# Blog
paginate:         5
paginate_path:    "/blog/page:num/"
permalink: /blog/:slug/

# Social for jekyll-seo-tag
twitter:
    username: "alex_gude"

social:
    name: "Alexander Gude"
    links:
        - https://twitter.com/alex_gude
        - https://github.com/agude
        - https://linkedin.com/in/AlexanderGude

# Google site verification via Jekyll-seo-tag
google_site_verification: NnoUcVom5yrsNeAcRLx7yQvWortvmqEP-yazzCmGSMA

# Google Analytics
google_analytics: UA-88777885-1

# SASS
sass:
    sass_dir: _sass
    style:    compressed

# Compress HTML http://jch.penibelst.de/
compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
        envs: []
    blanklines: false
    profile: false
    startings: []

# Excluded files from site
exclude:
    - LICENSE.md
    - CNAME
