# Dependencies
gems:
    - jekyll-paginate
    - jekyll-gist
    - jekyll-sitemap

# Permalinks
permalink:        pretty

# Setup
author:
    name: "Alexander Gude"

title:            "Alex Gude"
tagline:          "Data Scientist"
description:      "The home page and blog of Alexander Gude"

# URL
url:              http://alexgude.com
baseurl:          ""

# Blog
paginate:         5
paginate_path:    "/blog/page:num/"

# SASS
sass:
    sass_dir: _sass
    style:    compressed

# Compress HTML http://jch.penibelst.de/
compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
        envs: []
    blanklines: false
    profile: false
    startings: []
